# Generated by Django 3.1.5 on 2021-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('sec', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Formdata1',
        ),
    ]
